#' Calculate and plot probabilities of causal effect based on possible worlds
#'
#' This function calculates and plots the probabilities of positive causal effect, 
#' negative causal effect, and no causal effect based on prior success propensities for a 
#' dichotomous outcome. The plot visualizes these probabilities across different prior 
#' propensities, showing how the causal effect probabilities change with varying assumptions about 
#' the likelihood of success.
#'
#' @param CTEpr A list containing the distribution of the CTE generated by the \code{CTEprob} function.
#' @param epsilon A threshold for considering the CTE as different from 0. Default is 0.
#' @param displayepsilon Logical value indicating whether the \code{epsilon} threshold should be displayed in the plot. Default is \code{TRUE}.
#' @param addlegend Logical value indicating whether to add a legend to the plot. Default is \code{TRUE}.
#' @param colors A vector of colors used for plotting the three categories: No effect, Positive effect, and Negative effect. Default is \code{c("blue3", "green3", "red3")}.
#' @param add Logical value indicating whether to add to an existing plot (i.e., not creating a new plot). Default is \code{FALSE}.
#' @param lty Line type for the plot. Default is \code{1}.
#' @param lwd Line width for the plot. Default is \code{1}.
#' @param ylab Label for the y-axis. Default is \code{"Probability"}.
#' @param ylim y-axis limits. Default is \code{c(0, 1)}.
#' @param cex.legend Size of legend. Default is \code{c(0, 1)}.
#' @param \dots Additional graphical parameters passed to the plot function.
#'
#' @details
#' The causal effect categories are defined over the space of all possible worlds as:
#' \itemize{
#'   \item \eqn{E_{+, \epsilon} = \{ CTE > \epsilon \}} (Positive effect)
#'   \item \eqn{E_{-, \epsilon} = \{ CTE < -\epsilon \}} (Negative effect)
#'   \item \eqn{E_{0, \epsilon} = \{ |CTE| \leq \epsilon \}} (No effect)
#' }
#' The function calculates the probabilities of each of these events and plots them against the prior 
#' propensity values.
#'
#' @return 
#' A list containing the following probability vectors:
#' \itemize{
#'   \item p_positive_effect: Probability of a positive causal effect.
#'   \item p_negative_effect: Probability of a negative causal effect.
#'   \item p_no_effect: Probability of no causal effect.
#' }
#'
#'
#' @export
plotCTEprob <- function( CTEpr , epsilon=0, displayepsilon=T, addlegend=T, 
                         add=F, colors = c("blue3", "green3", "red3"),
                         lty=1, lwd=1, ylab = "Probability", ylim=c(0,1),
                         cex.legend=1, ...){
  
  p <- CTEpr$p
  
  # Computing probabilities of events E+, E- and E0. Exact and approximate methods.
  if ( is.null(CTEpr$masses) ) {
    dfaux <- data.frame( EpPi = CTEpr$Pi$EpPi , sqrtVpPi = sqrt(CTEpr$Pi$VpPi) )
    h <- hnormalcorrection(p1 = 1-CTEpr$probMZ$probK1Z1, n1 = CTEpr$probMZ$n1,
                           p0 = 1-CTEpr$probMZ$probK1Z0, n0 = CTEpr$probMZ$n0)
    p_positive_effect <- apply( dfaux , 1, function(x) {pnorm( epsilon + h/2 , x[1] , x[2] , lower.tail = F) } )
    p_negative_effect <- apply( dfaux , 1, function(x) {pnorm( -epsilon - h/2 , x[1] , x[2] , lower.tail = T) } )
    p_no_effect <- apply( dfaux , 1, function(x) {pnorm( epsilon  + h/2 , x[1] , x[2] , lower.tail = T) - pnorm( -epsilon  - h/2 , x[1] , x[2] , lower.tail = T) } )
    
  } else {
    masses <- CTEpr$masses
    
    # Calculating the probabilities of negative and positive causal effects
    p_negative_effect <- apply( masses[ masses$cte < -epsilon,-1] , 2, sum )
    p_positive_effect <- apply( masses[ masses$cte > epsilon,-1] , 2, sum )
    # Calculating the probabilities of no causal effects
    ine <- (masses$cte <= epsilon) & (masses$cte >= -epsilon)
    if ( sum( ine )>0 ) {
      p_no_effect <- apply( masses[ ine ,-1] , 2, sum )
    } else {
      p_no_effect <- rep( 0 , length(p_positive_effect) )
      names(p_no_effect) <- names(p_negative_effect)
    }
  }
  
  # Negative causal effect
  if (add) { # Drawing on existing plot
    lines( p , p_negative_effect , ylim=ylim,
           type = "l", col=colors[3], lty=lty , lwd=lwd)
  } else{ # New plot
    plot( p , p_negative_effect , ylim=ylim,
          type = "l", col=colors[3], lty=lty, las=1, ylab = "y", lwd=lwd)
  }
  # Positive causal effect
  lines( p , p_positive_effect ,
         type = "l", col=colors[2], lty=lty, lwd=lwd)
  
  if (addlegend) {
    legend("top", legend=c("No effect", "Possitive effect", "Negative effect"),
           col=colors, lty=1, xpd=TRUE, inset=c(0, -0.13),
           horiz=T, bty="n", text.width = NA, cex=cex.legend)
  }
  # No causal effect
  lines( p , p_no_effect , type = "l", col=colors[1],  lty=lty, lwd=lwd)
  
  # Adding the epsilon value at the bottom left
  if (displayepsilon) {
    mtext( paste0("epsilon=",epsilon), side = 1, line = 2, adj = 0, cex = 0.8)
  }
  
  # Returning probabilities
  invisible( list(p_positive_effect = p_positive_effect, 
                  p_negative_effect = p_negative_effect, 
                  p_no_effect = p_no_effect ) )
}

