#' Calculate and plot probabilities of causal effect based on possible worlds
#'
#' This function calculates and plots the probabilities of positive causal effect, 
#' negative causal effect, and no causal effect based on prior success propensities for a 
#' dichotomous outcome. The plot visualizes these probabilities across different prior 
#' propensities, showing how the causal effect probabilities change with varying assumptions about 
#' the likelihood of success.
#'
#' @param CTEpr A list containing the distribution of the CTE generated by the \code{CTEprob} function.
#' @param epsilon A threshold for considering the CTE as different from 0. Default is 0.
#' @param displayepsilon Logical value indicating whether the \code{epsilon} threshold should be displayed in the plot. Default is \code{TRUE}.
#' @param addlegend Logical value indicating whether to add a legend to the plot. Default is \code{TRUE}.
#' @param colors A vector of colors used for plotting the three categories: No effect, Positive effect, and Negative effect. Default is \code{c("blue3", "green3", "red3")}.
#' @param add Logical value indicating whether to add to an existing plot (i.e., not creating a new plot). Default is \code{FALSE}.
#' @param lty Line type for the plot. Default is \code{1}.
#' @param lwd Line width for the plot. Default is \code{1}.
#' @param ylab Label for the y-axis. Default is \code{"Probability"}.
#' @param ylim y-axis limits. Default is \code{c(0, 1)}.
#' @param cex.legend Size of legend. Default is \code{c(0, 1)}.
#' @param \dots Additional graphical parameters passed to the plot function.
#'
#' @details
#' The causal effect categories are defined over the space of all possible worlds as:
#' \itemize{
#'   \item \eqn{E_{+, \epsilon} = \{ CTE > \epsilon \}} (Positive effect)
#'   \item \eqn{E_{-, \epsilon} = \{ CTE < -\epsilon \}} (Negative effect)
#'   \item \eqn{E_{0, \epsilon} = \{ |CTE| \leq \epsilon \}} (No effect)
#' }
#' The function calculates the probabilities of each of these events and plots them against the prior 
#' propensity values.
#'
#' @return 
#' A list containing the following probability vectors:
#' \itemize{
#'   \item p_positive_effect: Probability of a positive causal effect.
#'   \item p_negative_effect: Probability of a negative causal effect.
#'   \item p_no_effect: Probability of no causal effect.
#' }
#'
#'
#' @export
plot.degreeoftruth <- function( 
    DegreesOfTruth, 
    showplot=T, 
    add=F, 
    displayepsilon=T, 
    addlegend=T, 
    colors = c("blue3", "green3", "red3"), 
    cex.legend=1, 
    legend.location = "topright", 
    displaytitle = T, 
    title.line = 1.2,
    lty=1:length(DegreesOfTruth), 
    lwd=1, 
    xlab = "Prior propensity p", 
    ylab = "Probability", 
    addCriteria = T,
    xmin = 0, xmax = 1, ymin = -0.02, ymax = 1.02, 
    xlab.line = 2.5, ...)
{
  
  p <- attr(DegreesOfTruth, "p")
  criteria <- attr(DegreesOfTruth, "criteria")
  epsilon  <- attr(DegreesOfTruth, "epsilon")
  
  if ( length(lty) != length(epsilon) ) {
    stop("Error: lty must have the same length of DegreesOfTruth")
  }
  
  # Create new plot
  if (!add) {
    gridplot(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax,
             xlab = xlab, ylab = ylab, xlab.line = xlab.line, ... )
  }
  
  if (addCriteria) {
    polygon( criteria[c(2,3,3,2)] , c( c(-1,-1) , rev(c(2,2)) ) ,  
             border = NA , col=AlphaCol("blue3",0.08) )
    abline( v = criteria[1], col=AlphaCol("gray",0.3) , lty=1, lwd=2)
  }
  
  for (eps in 1:length(epsilon)) {
    p_negative_effect <- DegreesOfTruth[[eps]]$p_negative_effect 
    p_positive_effect <- DegreesOfTruth[[eps]]$p_positive_effect
    p_no_effect       <- DegreesOfTruth[[eps]]$p_no_effect
    
    # Negative causal effect
    lines( p , p_negative_effect , 
           type = "l", col=colors[3], lty=lty[eps] , lwd=lwd)
    # Positive causal effect
    lines( p , p_positive_effect ,
           type = "l", col=colors[2], lty=lty[eps], lwd=lwd)
    # No causal effect
    lines( p , p_no_effect , type = "l", col=colors[1],  lty=lty[eps], lwd=lwd)
  }
  
  if (addlegend) {
    legend(x=legend.location, 
           legend = c( expression(E[0][","][epsilon]), 
                       expression(E["+"][","][epsilon]), 
                       expression(E["-"][","][epsilon]) ),
           col=colors, lty=1, xpd=TRUE, inset=c(0, -0.13), lwd=lwd,
           horiz=T, bty="n", text.width = NA, cex=cex.legend)
  }
  
  # Adding the epsilon value
  if (displayepsilon) {
    epsilontext <- ifelse( length(epsilon)>1 , paste(epsilon, collapse = ", ") , epsilon )
    title(main = bquote(epsilon ~ "=" ~ .(epsilontext) ) , cex.main = 0.8, adj = 0, line = 0.4)
  }
  
  # Adding title
  if (displaytitle) {
    title(main = expression(bold("Probabilities of" ~ E[paste("+",",", epsilon)] ~ "," ~ E[paste("-", ",", epsilon)] ~ "and" ~ E[paste("0", ",", epsilon)])),
          cex.main = 0.9, adj = 0, line = title.line)
  }
}
