# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CTEprobcpp <- function(n1, n2, a1, b1, a2, b2, p) {
    .Call('_ctepi_CTEprobcpp', PACKAGE = 'ctepi', n1, n2, a1, b1, a2, b2, p)
}

aggregate_cpp <- function(values, groups, levelgroup) {
    .Call('_ctepi_aggregate_cpp', PACKAGE = 'ctepi', values, groups, levelgroup)
}

ldbudboptimCpp <- function(y_values, F1, F2, F3, F4, x_limit, y_limit, delta = 0.1, addtoU = NULL) {
    .Call('_ctepi_ldbudboptimCpp', PACKAGE = 'ctepi', y_values, F1, F2, F3, F4, x_limit, y_limit, delta, addtoU)
}

massCpp <- function(matriz) {
    .Call('_ctepi_massCpp', PACKAGE = 'ctepi', matriz)
}

